name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deno Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3

      - name: Deploy to Deno
        uses: denoland/deployctl@v1
        with:
          project: adil-niz-new-checkup-89
          entrypoint: index.html
